### ISSUE TITLE
Versioning

### ISSUE THREAD

**Issue by spaulaus** [pixie16/PixieSuite2#60] opened 2015-10-09 20:48 UTC
It seems I made a snaffu with the versioning. There is a versioning system in place for the files individually, but not for the project as a whole. I will take care of organizing and standardizing this when I  work on the documentation for the software.

**Comment by ksmith0** [comment] 2016-08-29 19:23
Closed as duplicate of pixie16/paass#60

**Closed as completed by ksmith0** 2016-08-29 19:23 UTC
Labels: duplicate, enhancement
