### ISSUE TITLE
Voffset does not write properly - RevD

### ISSUE THREAD

**Issue by spaulaus** [pixie16/PixieSuite2#5] opened 2015-09-29 11:25 UTC
For the MTAS setup, the code was unable to write negative values for the VOFFSET. Any value that was inserted was corrected to zero. We are unable to reproduce this issue with Rev F.
### Pixie.cfg

PixieBaseDir      /home/pixie16/Pixie16RevD_General_1.4.3_Update_04072011
SpFpgaFile        firmware/fippixie16_revdgeneral_r16623.bin
ComFpgaFile       firmware/syspixie16_revdgeneral_r18101.bin
TrigFpgaFile      firmware/pixie16trigger.bin
DspConfFile       dsp/Pixie16DSP_r18419.ldr
DspVarFile        dsp/Pixie16DSP_r18419.var

**Comment by ksmith0** [comment] 2015-10-01 22:11
Is this still an issue?

**Comment by ksmith0** [comment] 2015-12-14 14:39
I believe this is an issue with have two spaces between the parameter name and the value. That would make this a duplicate of issue #82.

**Comment by ksmith0** [comment] 2015-12-14 15:31
The correction of issue #82 should resolve this. Needs testings.

**Comment by ksmith0** [comment] 2016-08-05 21:01
Any possibility we could close this?

**Comment by ksmith0** [comment] 2016-08-18 00:53
Closing this as the issue should have been resolved in issue #82

**Closed as completed by ksmith0** 2016-08-18 00:53 UTC
Labels: bug, duplicate, RevD
